name: flutter_google_places_hoc081098
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice. Better flutter_google_places, updated by @hoc081098
version: 2.0.0-beta.0
homepage: https://github.com/hoc081098/flutter_google_places
repository: https://github.com/hoc081098/flutter_google_places
funding:
  - https://www.buymeacoffee.com/hoc081098

topics:
  - rxdart
  - hoc081098
  - google-places
  - google-places-autocomplete
  - flutter-google-places

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.2.6
  http: ^1.0.0
  rxdart: ^0.28.0
  rxdart_ext: ^0.3.0
  listenable_stream: ^2.0.1
  collection: ^1.17.1
  flutter_bloc_pattern: ^3.0.0
  json_annotation: any
  meta: ^1.9.1
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  assets:
    - packages/flutter_google_places_hoc081098/assets/google_black.png
    - packages/flutter_google_places_hoc081098/assets/google_white.png
